### ISSUE TITLE
Solaire mode support

### ISSUE THREAD

**Issue by teutonicjoe** [catppuccin/emacs#41]
Thanks for this awesome package!!!!
It would be wonderful to see support for Solaire mode. I find it helps productivity a lot.

https://github.com/hlissner/emacs-solaire-mode

**Comment by NamesCode** [comment]
Hey could you elaborate for me?
I think we might already have Solaire support.

**Comment by averageflow** [comment]
Thanks for the reply! I mean that at least out-of-the box it doesn't seem to be working for me. 
Solaire mode's goal is to have some different colors (within same palette) for windows that are source code or main editing vs minibuffers and helper windows.

This really helps in productivity by being able to quickly distinguish for example your code from Magit.

In the screenshot you can see my config, I might possibly be doing something wrong?

![Schermafdruk_2023-01-08_11-49-55](https://user-images.githubusercontent.com/42377845/211192136-3865bf83-e571-4731-9918-46aa5d8b2101.png)

Solaire mode's docs say:
solaire-mode will disable itself if the active theme doesn't support it, but to ensure support a theme must at least change solaire-default-face's :background. My recommendation is that it is be slightly darker or lighter than default's background.

<p dir="auto">For full support, themes can customize the following faces:</p>


Face | Remapped face
-- | --
solaire-default-face | default
solaire-fringe-face | fringe
solaire-line-number-face | line-number
solaire-hl-line-face | hl-line
solaire-org-hide-face | org-hide, org-indent
solaire-mode-line-face | mode-line
solaire-mode-line-inactive-face | mode-line-inactive
solaire-header-line-face | header-line

**Comment by averageflow** [comment]
Doing a M-x describe-face -> solaire-default-face returns

```
Face: solaire-default-face (sample) (customize this face)

Documentation:
Alternative version of the ‘default’ face.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #181825
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```
